site_name: 'Agentic AI Knowledge Base'
site_description: 'A repository to consolidate knowledge articles, patterns, white papers, relevant articles supporting Agentic AI.'
site_author: 'Ankur Kumar'
docs_dir: 'docs'
site_dir: 'html'
theme:
  name: 'material'
  palette:
    primary: indigo
  features:
    - navigation.instant
    - search.highlight

nav:
  - Home: 'index.md'
  - Foundations: 'Foundations/Readme.md'
  - Agentic Frameworks: 'AgenticFrameworks/README.md'
  - Agent Platforms: 'AgentPlatforms/README.md'
  - Agentic Tech Stack: 'AgenticTechStack/README.md'
  - Context Engineering: 'ContextEngineeeing/README.md'
  - Agent Memory: 'AgentMemory/README.md'
  - Prompt Engineering: 'PromptEngineering/README.md'
  - Agent Code Sandbox: 'CodeSandbox/README.md'
  - Design Patterns: 'DesignPatterns/Readme.md'
  - Agentic Maturity Models: 'MaturityModels/README.md'
  - Retrieval Approaches: 'RetrievalApproaches/README.md'
  - MCP: 'MCP/README.md'
  - Reference Architecture: 'ReferenceArchitecture/README.md'
  - Code Repositories: 'CodeExamples/README.md'
  - Best Practices: 'BestPractices/README.md'
  - Dev/Coding Agents: 'DevAgents/Readme.md'
  - Research Agents: 'ResearchAgents/Readme.md'
  - Web Search & Crawl: 'WebSearchCrawl/README.md'
  - Standards: 'Standards/README.md'
  - Research: 'Research/README.md'
  - Benchmarks: 'Benchmarks/Readme.md'
  - LLMs: 'LLM/README.md'
  - Evaluation Frameworks: 'EvaluationFrameworks/Readme.md'  
  - SaaS Platforms: 'SaaSPlatforms/README.md'
  - Workflow Builders: 'WorkflowBuilders/README.md'
  - Observability: 'Observability/Readme.md'
  - SampleApps: 'SampleApps/Readme.md'
  - Security Frameworks: 'SecurityFrameworks/Readme.md'
  - Marketplace: 'Marketplace/Readme.md'
  - LLM/AI Gateway: 'LLMGateway/Readme.md'
  - Caching: 'Caching/README.md'
  - Cloud Hosting: 'CloudHosting/README.md'
  - RAG: 'RAG/Readme.md'
  - Newsletter & Blogs: 'NewsletterBlogs/README.md'
  - Courses: 'Courses/README.md'
  - All Things Google: 'AllThingsGoogle/README.md'
  - All Things AWS: 'AllThingsAWS/README.md'
  - All Things Microsoft: 'AllThingsMicrosoft/README.md'
  - Gartner: 'Gartner/README.md'
plugins:
  - search
  - mermaid2
  - markdown-filter:
      levels: [1, 2]
  - macros
  - awesome-pages
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
